<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="MyRobot" >

  <property name="mb_pi" value="3.14159265" />
  <property name="mb_mass" value="22.2260" />
  
  <property name="chassis_sx" value="0.7874" />
  <property name="chassis_sy" value="0.5334" />
  <property name="chassis_sz" value="0.0762" />

  <property name="wheel_height" value="0.0470" />
  <property name="wheel_radius" value="0.0758" />
  <property name="wheel_axis_offset" value="0.3494" />
  <property name="wheel_chassis_offset" value="0.0093" />
  <property name="wheel_mass" value="0.9072" />
  <property name="wheel_joint_urdf_max_effort" value="100.0" />
  <property name="wheel_joint_urdf_max_velocity" value="100.0" />
  <property name="wheel_joint_urdf_damping" value="0.0" />
  <property name="wheel_joint_urdf_friction" value="0.0" />

  <!-- /////////////////////////////////////////////////////////////////////////////////////// -->
  <!-- Macros definition. -->
  <!-- /////////////////////////////////////////////////////////////////////////////////////// -->
  <xacro:macro name="box_inertia" params="sizeX sizeY sizeZ mass *origin">
    <inertial>
      <mass value="${mass}" />
      <insert_block name="origin" />
      <inertia ixx="${mass / 12 * (sizeY * sizeY + sizeZ * sizeZ)}" ixy="0.0" ixz="0.0"
               iyy="${mass / 12 * (sizeX * sizeX + sizeZ * sizeZ)}" iyz="0.0"
               izz="${mass / 12 * (sizeX * sizeX + sizeY * sizeY)}" />
    </inertial>
  </xacro:macro>
  
  <xacro:macro name="sphere_inertia" params="radius mass *origin">
    <inertial>
      <mass value="${mass}" />
      <insert_block name="origin" />
      <inertia ixx="${2.0 / 5.0 * mass * radius * radius}" ixy="0.0" ixz="0.0"
               iyy="${2.0 / 5.0 * mass * radius * radius}" iyz="0.0"
               izz="${2.0 / 5.0 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>
  
  <xacro:macro name="mr_wheel" params="fb lr parent sideX sideY scaleXZ">
    <joint name="${fb}_${lr}_wheel_joint" type="continuous">
      <parent link="${parent}" />
      <child link="${fb}_${lr}_wheel" />
      <origin xyz="${sideX * wheel_axis_offset} ${sideY * (chassis_sy / 2.0 + wheel_chassis_offset + wheel_height / 2.0)} ${wheel_radius}" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />
      <limit effort="${wheel_joint_urdf_max_effort}" velocity="${wheel_joint_urdf_max_velocity}"/>
      <dynamics damping="${wheel_joint_urdf_damping}" friction="${wheel_joint_urdf_friction}"/>
    </joint>

    <link name="${fb}_${lr}_wheel" >
      <visual>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </collision>
      <xacro:sphere_inertia radius="${wheel_radius}" mass="${wheel_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </xacro:sphere_inertia>
    </link>

    <transmission name="${fb}_${lr}_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${fb}_${lr}_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface> <!-- Duplicate in "actuator" tag but for some reason this duplication is needed. Check http://answers.ros.org/question/186681/no-valid-hardware-interface-element-found-in-joint/ -->
      </joint>
      <actuator name="${fb}_${lr}_wheel_motor">
        <hardwareInterface>VelocityJointInterface</hardwareInterface> <!-- Duplicate in "joint" tag but for some reason this duplication is needed. Check http://answers.ros.org/question/186681/no-valid-hardware-interface-element-found-in-joint/  -->
        <mechanicalReduction>12.75</mechanicalReduction>
      </actuator>

    </transmission>
  </xacro:macro>

  <!-- /////////////////////////////////////////////////////////////////////////////////////// -->
  <!-- Robot's definition. -->
  <!-- /////////////////////////////////////////////////////////////////////////////////////// -->

  <!-- Chassis. -->
  <link name="chassis" >
    <visual>
      <geometry>
        <box size="${chassis_sx} ${chassis_sy} ${chassis_sz}" />
      </geometry>
      <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_sx} ${chassis_sy} ${chassis_sz}" />
      </geometry>
      <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0" />
    </collision>
    <xacro:box_inertia sizeX="${chassis_sx}" sizeY="${chassis_sy}" sizeZ="${chassis_sz}" mass="${mb_mass - 4 * wheel_mass}">
      <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0" />
    </xacro:box_inertia>
  </link>

  <!-- Wheels. -->
  <xacro:mr_wheel fb="front" lr="left" parent="chassis" sideX="1.0" sideY="1.0" scaleXZ="1.0" />
  <xacro:mr_wheel fb="back" lr="left" parent="chassis" sideX="-1.0" sideY="1.0" scaleXZ="-1.0" />
  <xacro:mr_wheel fb="back" lr="right" parent="chassis" sideX="-1.0" sideY="-1.0" scaleXZ="1.0" />
  <xacro:mr_wheel fb="front" lr="right" parent="chassis" sideX="1.0" sideY="-1.0" scaleXZ="-1.0" />

</robot>
