manipulator:
  kinematics_solver: ur_kinematics/UR3KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 30.0 # Changed from 0.005 to 0.01 and 0.1 and 5.0 (simulation)
  kinematics_solver_attempts: 5

#manipulator:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
